---
- hosts: all
  user: root
  tasks:
    - name: ssh-copy
      authorized_key: 
        user: root 
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      tags:
        - sshkey

- hosts: network
  roles:
#    - role: network
#    - role: common

- hosts: master 
  roles:
    - role: master

- hosts: worker
  roles:
    - role: worker 

