---
- hosts: pre-servers
  user: root
  tasks:
    - name: ssh-copy
      authorized_key: 
        user: root 
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      tags:
        - sshkey

- hosts: network
  roles:
    - role: network

